class Orchard < Formula
  desc "Terminal-native companion for Claude Code multi-agent sessions"
  homepage "https://github.com/hcarminati/orchard"
  license "MIT"

  # This file is a template. The actual formula in the homebrew-orchard tap
  # is generated by the release workflow and has the correct version/sha256.
  # See .github/workflows/release.yml for how it is updated.
  #
  # To add Orchard via Homebrew:
  #   brew tap hcarminati/tap
  #   brew install orchard

  on_macos do
    on_arm do
      url "https://github.com/hcarminati/orchard/releases/download/v#{version}/orchard_#{version.to_s.delete_prefix("v")}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_darwin_arm64_sha256"
    end

    on_intel do
      url "https://github.com/hcarminati/orchard/releases/download/v#{version}/orchard_#{version.to_s.delete_prefix("v")}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_darwin_amd64_sha256"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hcarminati/orchard/releases/download/v#{version}/orchard_#{version.to_s.delete_prefix("v")}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_linux_arm64_sha256"
    end

    on_intel do
      url "https://github.com/hcarminati/orchard/releases/download/v#{version}/orchard_#{version.to_s.delete_prefix("v")}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_linux_amd64_sha256"
    end
  end

  def install
    bin.install "orchard"
  end

  def caveats
    <<~EOS
      Run `orchard setup` to wire up the Claude Code hook integration:

        orchard setup

      This non-destructively adds hook entries to ~/.claude/settings.json.
      Run `orchard doctor` to verify the setup is working correctly.

      Then open a split pane and run `orchard` alongside Claude Code.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/orchard --version")
  end
end
